# Generated by Django 5.1.6 on 2025-02-20 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('RESOLUTION_ADD', 'Resolution Add'), ('SOLUTION_ASSOCIATION', 'Solution Association'), ('RESOLUTION_UPDATE', 'Resolution Update'), ('RESOLVED', 'Resolved'), ('DELETE', 'Delete'), ('RESTORE', 'Restore'), ('REQ_CONVER', 'Req Conver'), ('SLA_VIOLATION', 'SLA Violation'), ('ADD_REQUEST_TASK', 'Add Request Task'), ('COMPLETED', 'Completed'), ('CLOSE', 'Close')], max_length=25)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.case')),
            ],
        ),
    ]
