# Generated by Django 5.1.6 on 2025-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rework',
            name='target',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
