# Generated by Django 5.1.6 on 2025-03-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
