# Generated by Django 5.1.6 on 2025-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rework_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
