# Generated by Django 5.1.6 on 2025-02-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='number_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variant',
            name='activities',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variant',
            name='cases',
            field=models.CharField(max_length=50),
        ),
    ]
