# Generated by Django 5.1.6 on 2025-02-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invoice_delete_activity_delete_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='confidence',
            field=models.CharField(default='High', max_length=6),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='group_id',
            field=models.CharField(max_length=50),
        ),
    ]
