# Generated by Django 5.1.6 on 2025-02-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_variant_number_cases_alter_variant_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
