NAMES = [
    "Aaron", "Abigail", "Adam", "Adrian", "Aiden", "Alan", "Albert", "Alex", "Alexander", "Alexis",
    "Alice", "Alicia", "Allison", "Alyssa", "Amanda", "Amber", "Amy", "Andrea", "Andrew", "Angela",
    "Anna", "Anthony", "Ashley", "Austin", "Ava", "Barbara", "Benjamin", "Betty", "Beverly", "Billy",
    "Bobby", "Brandon", "Brenda", "Brian", "Brittany", "Bruce", "Bryan", "Caitlin", "Caleb", "Cameron",
    "Carl", "Carol", "Carolyn", "Catherine", "Charles", "Charlotte", "Cheryl", "Christian", "Christina", "Christine",
    "Christopher", "Cindy", "Claire", "Clara", "Clarence", "Claudia", "Clayton", "Clifford", "Clinton", "Cody",
    "Colin", "Connor", "Courtney", "Craig", "Crystal", "Curtis", "Cynthia", "Daisy", "Dakota", "Dale",
    "Daniel", "Danielle", "Darlene", "David", "Dawn", "Dean", "Deborah", "Debra", "Denise", "Dennis",
    "Derek", "Diana", "Diane", "Donald", "Donna", "Doris", "Dorothy", "Douglas", "Dylan", "Earl",
    "Edgar", "Edith", "Edmund", "Edward", "Edwin", "Elaine", "Eleanor", "Elena", "Eli", "Elijah",
    "Elizabeth", "Ella", "Ellen", "Emily", "Emma", "Eric", "Erica", "Erik", "Erin", "Ethan",
    "Eugene", "Eva", "Evan", "Evelyn", "Faith", "Faye", "Felicia", "Felix", "Fiona", "Florence",
    "Frances", "Francis", "Frank", "Franklin", "Fred", "Frederick", "Gabriel", "Gail", "Gary", "Gavin",
    "Gene", "Geoffrey", "George", "Georgia", "Gerald", "Geraldine", "Gilbert", "Gina", "Glen", "Glenda",
    "Gloria", "Grace", "Graham", "Grant", "Gregory", "Gretchen", "Guy", "Hailey", "Hannah", "Harold",
    "Harry", "Hazel", "Heather", "Hector", "Helen", "Henry", "Herbert", "Herman", "Holly", "Howard",
    "Hugh", "Hunter", "Ian", "Irene", "Isaac", "Isabel", "Isabella", "Isaiah", "Ivan", "Jack",
    "Jackie", "Jacob", "Jacqueline", "James", "Jamie", "Jane", "Janet", "Janice", "Jared", "Jason",
    "Jean", "Jeffrey", "Jenna", "Jennifer", "Jeremy", "Jerry", "Jesse", "Jessica", "Jill", "Joan",
    "Joanna", "Joe", "Joel", "John", "Johnny", "Jonathan", "Jordan", "Joseph", "Joshua", "Joyce",
    "Juan", "Judith", "Judy", "Julia", "Julian", "Julie", "Justin", "Karen", "Katherine", "Kathleen",
    "Kathryn", "Kathy", "Katie", "Kayla", "Keith", "Kelly", "Kenneth", "Kevin", "Kimberly", "Kirk",
    "Kristen", "Kristin", "Kyle", "Lance", "Larry", "Laura", "Lauren", "Laverne", "Lawrence", "Leah",
    "Lee", "Leonard", "Leslie", "Lewis", "Lillian", "Linda", "Lindsay", "Lisa", "Logan", "Lois",
    "Lori", "Louis", "Lucas", "Luis", "Luke", "Lydia", "Lynn", "Madeline", "Madison", "Maggie",
    "Malcolm", "Mandy", "Manuel", "Marc", "Marcia", "Margaret", "Maria", "Marie", "Marilyn", "Marion",
    "Marjorie", "Mark", "Marlene", "Marshall", "Martha", "Martin", "Marvin", "Mary", "Mason", "Matthew",
    "Maureen", "Megan", "Melanie", "Melissa", "Melvin", "Meredith", "Michael", "Michele", "Michelle", "Mildred",
    "Milton", "Miranda", "Mitchell", "Molly", "Monica", "Morgan", "Nancy", "Natalie", "Nathan", "Nathaniel",
    "Neal", "Neil", "Nicholas", "Nicole", "Nina", "Noah", "Nolan", "Norma", "Norman", "Olivia",
    "Oscar", "Owen", "Pamela", "Patricia", "Patrick", "Paul", "Paula", "Peggy", "Penny", "Peter",
    "Philip", "Phillip", "Phyllis", "Preston", "Priscilla", "Quentin", "Quincy", "Rachel", "Ralph", "Randy",
    "Raymond", "Rebecca", "Regina", "Renee", "Rhonda", "Richard", "Rick", "Ricky", "Rita", "Robert",
    "Roberta", "Robin", "Roger", "Ronald", "Rosa", "Rose", "Rosemary", "Ross", "Roy", "Ruby",
    "Russell", "Ruth", "Ryan", "Sabrina", "Sally", "Samantha", "Samuel", "Sandra", "Sara", "Sarah",
    "Scott", "Sean", "Shane", "Shannon", "Sharon", "Sheila", "Shelby", "Sherri", "Sherry", "Shirley",
    "Sidney", "Sierra", "Simon", "Sonia", "Sophia", "Spencer", "Stacey", "Stacy", "Stanley", "Stephanie",
    "Stephen", "Steve", "Steven", "Stuart", "Sue", "Susan", "Suzanne", "Sydney", "Sylvia", "Tamara",
    "Tammy", "Tanya", "Tara", "Taylor", "Ted", "Teresa", "Terrence", "Terry", "Theodore", "Theresa",
    "Thomas", "Tiffany", "Timothy", "Tina", "Todd", "Tommy", "Toni", "Tony", "Tracy", "Travis",
    "Trent", "Trevor", "Tricia", "Troy", "Tyler", "Valerie", "Vanessa", "Vera", "Veronica", "Victor",
    "Victoria", "Vincent", "Virginia", "Vivian", "Walter", "Wanda", "Wayne", "Wendy", "Wesley", "Whitney",
    "William", "Willie", "Wyatt", "Xavier", "Yolanda", "Yvonne", "Zachary", "Zoe"
]

RAMOS = [
    "Home Insurance",
    "Fire Insurance",
    "Life Insurance",
    "Health Insurance",
    "Auto Insurance",
    "Travel Insurance",
    "Pet Insurance",
    "Business Insurance",
    "Renters Insurance",
    "Flood Insurance",
    "Earthquake Insurance",
    "Disability Insurance",
    "Liability Insurance",
    "Workers' Compensation Insurance",
    "Cyber Insurance",
    "Marine Insurance",
    "Aviation Insurance",
    "Crop Insurance",
    "Title Insurance",
    "Burial Insurance"
]

BRANCHES = [
    "Branch 1",
    "Branch 2",
    "Branch 3",
    "Branch 4",
    "Branch 5",
    "Branch 6",
    "Branch 7",
    "Branch 8",
    "Branch 9",
    "Branch 10"
]